spring:
  application:
    name: WeddingApplication
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: ${SECRET_KEY}